const rookies2020Draft = {
    'Anthony Edwards':true,
    'James Wiseman':true,
    'LaMelo Ball':true,
    'Patrick Williams':true,
    'Isaac Okoro':true,
    'Onyeka Okongwu':true,
    'Killian Hayes':true,
    'Obi Toppin':true,
    'Deni Avdija':true,
    'Jalen Smith':true,
    'Devin Vassell':true,
    'Tyrese Haliburton':true,
    'Kira Lewis Jr.':true,
    'Aaron Nesmith':true,
    'Cole Anthony':true,
    'Isaiah Stewart':true,
    'Aleksej Pokuševski':true,
    'Josh Green':true,
    'Saddiq Bey':true,
    'Precious Achiuwa':true,
    'Tyrese Maxey':true,
    'Zeke Nnaji':true,
    'Leandro Bolmaro':true,
    'R. J. Hampton':true,
    'Immanuel Quickley':true,
    'Payton Pritchard':true,
    'Udoka Azubuike':true,
    'Jaden McDaniels':true,
    'Malachi Flynn':true,
    'Desmond Bane':true,
    'Tyrell Terry':true,
    'Vernon Carey Jr.':true,
    'Daniel Oturu':true,
    'Théo Maledon':true,
    'Xavier Tillman':true,
    'Tyler Bey':true,
    'Vít Krejčí':true,
    'Saben Lee':true,
    'Elijah Hughes':true,
    'Robert Woodard II':true,
    'Tre Jones':true,
    'Nick Richards':true,
    "Jahmi'us Ramsey":true,
    'Marko Simonović':true,
    'Jordan Nwora':true,
    'C. J. Elleby':true,
    'Yam Madar':true,
    'Nico Mannion':true,
    'Isaiah Joe':true,
    'Skylar Mays':true,
    'Justinian Jessup':true,
    'Kenyon Martin Jr.':true,
    'Cassius Winston':true,
    'Cassius Stanley':true,
    'Jay Scrubb':true,
    'Grant Riller':true,
    'Reggie Perry':true,
    'Paul Reed':true,
    'Jalen Harris':true,
    'Sam Merrill':true,
}

const rookies2020Undrafted = {}


exports.rookies2020Draft = {...rookies2020Draft,...rookies2020Undrafted};
